### ISSUE TITLE
cfparam with default being flagged as error

### ISSUE THREAD

**Issue by john42** [softwareCobbler/cfc#2]
If I have the code 

cfparam(name="sid", default="0");

it gets flagged with the error "Reserved keyword 'default' cannot be used as an identifier".

**Comment by softwareCobbler** [comment]
this is fixed in 1.0.26, which will be live in the next hour or so. We'd like to keep offering checks for invalid identifiers, but we're looking into the best way to formalize it.

In adobe, `<cfset var try = 42>` is valid, but `<cfscript>var try = 42;</cfscript>` is an error. In lucee, they're both valid. Other keywords are variably valid or invalid depending on lexical position and execution engine. So we need to offer different language modes, and check context. Incidentally, are you running adobe or lucee (or something else?)

**Comment by john42** [comment]
Thanks David, that fixed it.

Strange that the CFSCRIPT version above errors out while the other does
not, basically doing the exact same thing. If you change it
to  <cfscript>local.try = 42;</cfscript> it works. Could be it's getting
mixed up with the keyword "try"?

BTW. I am usu=ing ACF 2018

John

**Comment by softwareCobbler** [comment]
thanks for the feedback, we appreciate it!
